os:
  - linux
language: c++
sudo: false
cache: apt
addons:
  apt:
    sources:
    - kalakris-cmake
    - ubuntu-toolchain-r-test
    - cassou-emacs
    packages:
    - emacs24
    - mercurial
    - python2.7
    - texlive-latex-recommended
    - texlive-humanities
    - texlive-xetex
    - texlive-science
    - texlive-latex-extra
    - texlive-luatex
    - texlive-fonts-recommended
    - latexmk
    - latex-xcolor
    - lmodern
    - dvipng
    - pgf
    - moreutils
    - nodejs
    - g++-4.8
    - libstdc++-4.8-dev
    - libgmp-dev
    - libmpfr-dev
    - liblua5.2-dev
    - cmake
env:
  global:
   # Result of "travis encrypt -r leanprover/logic_and_proof GH_TOKEN=<GH_TOKEN>"
   # (to push to leanprover org)
   - secure: "fUbztAm6wloIx6x5it31sW5EhOY6xkbplwq+mZGkVGtHQpJfAlvPi/ae2heBjsPsBsl8Wvw3mhtRwvEnfV0SLPG9st/SYYvXZ7PL/wSnvsD0KsuNf0eOtq9W2NKOATyZAq0FcIZkxD8IwqNgI10xmEnO4rK5Jg9lPTBA+wo4e1mxPo5pUceUZ8F4RLjB5aUvtBKfN5qocjEsRKsmSU8jyNvTCrPTW+7dQF2dyQMZpyopWpDG7+t1cz2mXgmtzS41FebnJc4k49G6idDoqYswzgb3/Zb7uZqIIYYmSeAYdMqUEibPQ42nWo9Unj3G/yxD1OdHRHYRnNUR87YCOkA/6ZOBuCdPoIEf9H9wX4T6xcUyPiu2dc1uTJUAxYNrv2QVtisM3Zyt0E66HHzjwWl6Erxq9SmYqEW1pZWezwomGrv+xx8BYggBZTLIvtrM35OGO89YWOOtBm0H/6VlsoPPZwWRkU5u0BVjpo8Tf6BcUgV9OLiaIj6Dh0Go8B/Mo/AibMMyWotOZrn95N0XDjf0LPBs05gfBzY2p77hXkMr/m5WKrTo649svpUeXEaJfjE9a5Hdh26qe0oNYcCG+Y8z/j8QzZZ+C5ZFbH3i8jDC6kxzTptuuPIxSPhYItLp4Jp+/SEFc8hSlovWVi40bD5TZGnm0BxylA9uhyRo6xGPAz4="
   # Result of "travis encrypt -r leanprover/logic_and_proof
   # (to perform extra stuff only for pushes to the blessed repo)
   - secure: "YvzXAe+I0+IcymptNjhb6R+5FE6KDC0VnuGBqUwtSsmOB0hu2loqdG+3YPjvW0MfQGrSuwBh4wLIgluFLubHtPh7g83thZhIer1cIPVhCVtEvbdM9vdzwQNrHht7BuK8BFFTeyusud7oyD9QgcjE13q014VxD+xwU/JeXbZ1Zo02E2K8HbCzNuQvFfnmnXjQ9fEvOI8jxTLgZcjtw4B0cWc0b5OcHNUqU2wREUSjJ7R2P9EODITtIG9N7ZJr3IbTWu1SBX6xOi3wJBHcQ6Oi7rxbJ6fefCKMxMBBVpEkcb84VRKnTOyWueNRCgFad4BIUdHnFsEeSXmcP0x0wt0VG42ImEv+rZbBB8LOKyJeTkj8Yecftf53aKHP/cjCrecrkMeCkID3Ib6X3A9I/Y6sCtLdhPCEK+njU679Da9gFM+RwFXV7x9fClY0NOf7MuUKAQuQ3JzV+T/cj2eGQa9gxyxEPaqwdNkrwGAZZxzFrbR/ofaFEWmj0jkWEo6yqts26NalxnmPzpLGJXmHSM2LdOdgtLrTSLbzxPGubAVzg2seovDzc2m7CWC/HFFTyaoLtUHpSy9ClJPWwxxUhBKuxXSKsKHHitn9+aaQ6B62sCoiNYcIo7DdhAroVMwvtcfmnU+VWkjKV62eGY6+Kqak0Ld+WaOsAjIYOcF30/ejLxU="
  matrix:
   - TEST=TRUE

before_install:
  - mkdir ~/bin
  - export PATH="/home/travis/.cask/bin:~/bin:$PATH"
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask
  - tar xvfz header/l3kernel.tar.gz -C ~/

install:
  # Install Lean dependencies
  - npm -g i cssmin minify
  - git clone https://github.com/leanprover/lean
  # Build Lean
  - if [[ $TEST == TRUE ]] ; then
      cd lean &&
      mkdir build &&
      cd build &&
      cmake -DIGNORE_SORRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-4.8 ../src &&
      make &&
      cd ../../;
    fi
  # bibtex2html
  - wget --no-check-certificate http://www.lri.fr/\~filliatr/ftp/bibtex2html/bibtex2html-1.98-linux.tar.gz
  - tar xvfz bibtex2html-1.98-linux.tar.gz
  - cp -v bibtex2html-1.98-linux/* ~/bin
  - rm -rf bibtex2html-1.98-linux bibtex2html-1.98-linux.tar.gz

script:
  - EMACS_BIN=emacs make
  # Build completion.js
  - echo "var completions = [" > js/completion.js
  - lean --server < js/completion_input.in | grep "|" | grep -v "^private\." | sort | uniq | sed -e "s/\([^|]\+\)|\(.\+\)/{name:\"\1\", value:\"\1\", meta:\"\2\"},/" >> js/completion.js
  - echo "]" >> js/completion.js
  # Build input-method.js
  - emacs --no-site-file --no-site-lisp -q --batch -l ./elisp/org-html-export.el -l ./lean/src/emacs/lean-input.el -f lean-input-export-translations-to-stdout > js/input-method.js
  # Push to gh-pages
  - if [[ "${REPO}" == "BLESSED" ]] && [[ "${TRAVIS_PULL_REQUEST}" == "false" ]] ; then
      git config --global user.email "notifications@travis-ci.org" &&
      git config --global user.name "Travis CI" &&
      git checkout --orphan gh-pages &&
      rm -f .git/index &&
      git add -f *.html logic_and_proof.pdf &&
      for CSS in css/*.css; do cssmin ${CSS} | sponge ${CSS} ; done &&
      git add css &&
      git add ltxpng &&
      git add images &&
      git add fonts &&
      for JS in js/*.js; do minify ${JS} | sponge ${JS} ; done &&
      git add -f js/* &&
      rm -rf pygments-main &&
      git clean -fxd &&
      git commit -m "Update `date -R`" &&
      git push -q https://soonhokong:${GH_TOKEN}@github.com/leanprover/logic_and_proof.git +HEAD:gh-pages &&
      git checkout -f master;
    fi
  # Test
  - if [[ $TEST == TRUE ]] ; then
        LEAN_BIN=lean/bin/lean make -j2 test;
    fi
  - if [[ $TEST_JS == TRUE ]] ; then
        make -j2 test_js;
    fi

notifications:
  email:
    recipients:
     - lean-build@googlegroups.com
